services:
  - type: web
    name: Bhojanly-web
    env: python
    plan: free
    repo: ${REPO}
    branch: main
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn Bhojanly.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DEBUG
        value: ${DEBUG}
      - key: ALLOWED_HOSTS
        value: ${ALLOWED_HOSTS}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
