# Generated by Django 5.2.5 on 2025-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_deliverypartner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
