# Generated by Django 5.2.5 on 2025-12-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_deliverypartner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='deliverypartner',
            name='otp_verified',
        ),
    ]
