# Generated by Django 5.2.5 on 2025-12-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_deliverypartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
