# Generated by Django 5.2.5 on 2025-12-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deliverypartner_otp_deliverypartner_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='username',
            field=models.CharField(default='temp_user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
